### ISSUE TITLE
Build error in the package

### ISSUE THREAD

**Issue by lizlove** [zeke/ap-style-title-case#1]
```
ERROR in ./~/ap-style-title-case/index.js
Module build failed: Error
    at new JS_Parse_Error (eval at <anonymous> (/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
```

I've been trying to build the package in npm and keep getting the following error. Any ideas as to the issue?

**Comment by zeke** [comment]
What version of node are you using?

**Comment by zeke** [comment]
Closing this due to inactivity. Feel free to comment here if this issue persists.
